

DECLARE @CODPROD INT,
	@REFERENCIA CHAR,
	@FOB FLOAT,
	@ORIGEMPROD INT,
	@CUSTO FLOAT,
	@DTATUAL DATETIME

DECLARE BUSCAR_PRODUTOS CURSOR FOR
	
	SELECT A.CODPROD, A.REFERENCIA, A.AD_FOBDOLAR AS FOB, A.ORIGPROD AS ORIGEMPROD, A.CUSTO, A.DTATUAL
	FROM (
	SELECT DISTINCT PRO.CODPROD, 
		PRO.REFERENCIA, 
		PRO.AD_FOBDOLAR,
		PRO.ORIGPROD,
		(SELECT TOP 1 CUSREP FROM TGFCUS CUS WHERE CUS.CODPROD = PRO.CODPROD ORDER BY DTATUAL DESC) CUSTO,
		(SELECT TOP 1 DTATUAL FROM TGFCUS CUS WHERE CUS.CODPROD = PRO.CODPROD ORDER BY DTATUAL DESC) DTATUAL

	FROM TGFPRO PRO
	WHERE  PRO.ORIGPROD = 1 AND ATIVO = 'S' AND (PRO.AD_FOBDOLAR IS NOT NULL OR PRO.AD_FOBDOLAR > 0)
	)A 
	WHERE A.CUSTO IS NOT NULL AND A.AD_FOBDOLAR > 0  AND A.DTATUAL > '2022/11/30'

OPEN BUSCAR_PRODUTOS 

FETCH NEXT FROM BUSCAR_PRODUTOS INTO @CODPROD, @REFERENCIA, @FOB, @ORIGEMPROD, @CUSTO, @DTATUAL

WHILE @@FETCH_STATUS = 0
BEGIN

	IF (@CUSTO <> @FOB)
	BEGIN
		UPDATE TGFCUS SET CUSREP = @FOB WHERE CODPROD = @CODPROD AND DTATUAL = (SELECT TOP 1 DTATUAL FROM TGFCUS CUS WHERE CUS.CODPROD = @CODPROD ORDER BY DTATUAL DESC)
	END

FETCH NEXT FROM BUSCAR_PRODUTOS INTO @CODPROD, @REFERENCIA, @FOB, @ORIGEMPROD, @CUSTO, @DTATUAL
END
CLOSE BUSCAR_PRODUTOS
DEALLOCATE BUSCAR_PRODUTOS
